version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/controle-financeiro-go
    depends_on:
      - database
    container_name: controle-financeiro-go-web
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'

  database:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: controle-financeiro-go
    container_name: controle-financeiro-go-db
    ports:
      - 33066:3306
    volumes:
      - controle-financeiro-go-data:/var/lib/mysql 

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 5003:80
    environment:
      - 'PMA_HOST=database'
      - 'PMA_PORT=3306'
    container_name: controle-financeiro-go-pma


# persisted storage
volumes:
  controle-financeiro-go-data: